Resources:
  CircuitBreakerTable02DAD2B8:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/CircuitBreakerTable/Resource
  UnreliableLambdaHandlerServiceRole955A5CFD:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/UnreliableLambdaHandler/ServiceRole/Resource
  UnreliableLambdaHandlerServiceRoleDefaultPolicyC00E31E2:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CircuitBreakerTable02DAD2B8
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: UnreliableLambdaHandlerServiceRoleDefaultPolicyC00E31E2
      Roles:
        - Ref: UnreliableLambdaHandlerServiceRole955A5CFD
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/UnreliableLambdaHandler/ServiceRole/DefaultPolicy/Resource
  UnreliableLambdaHandlerD4A4DED9:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersa0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43S3BucketF9D2DE3B
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43S3VersionKey915B853C
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43S3VersionKey915B853C
      Handler: unreliable.handler
      Role:
        Fn::GetAtt:
          - UnreliableLambdaHandlerServiceRole955A5CFD
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          CIRCUITBREAKER_TABLE:
            Ref: CircuitBreakerTable02DAD2B8
    DependsOn:
      - UnreliableLambdaHandlerServiceRoleDefaultPolicyC00E31E2
      - UnreliableLambdaHandlerServiceRole955A5CFD
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/UnreliableLambdaHandler/Resource
      aws:asset:path: asset.a0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43
      aws:asset:property: Code
  CircuitBreakerGateway122B123C:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: CircuitBreakerGateway
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/CircuitBreakerGateway/Resource
  CircuitBreakerGatewayDefaultRouteTheLambdaCircuitBreakerStackCircuitBreakerGatewayDefaultRoute883D7748Permission8BF71621:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - UnreliableLambdaHandlerD4A4DED9
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: CircuitBreakerGateway122B123C
            - /*/*
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/CircuitBreakerGateway/DefaultRoute/TheLambdaCircuitBreakerStackCircuitBreakerGatewayDefaultRoute883D7748-Permission
  CircuitBreakerGatewayDefaultRouteDefaultRouteIntegrationF55AEBDB:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: CircuitBreakerGateway122B123C
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - UnreliableLambdaHandlerD4A4DED9
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/CircuitBreakerGateway/DefaultRoute/DefaultRoute-Integration/Resource
  CircuitBreakerGatewayDefaultRouteCB8326BD:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: CircuitBreakerGateway122B123C
      RouteKey: $default
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: CircuitBreakerGatewayDefaultRouteDefaultRouteIntegrationF55AEBDB
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/CircuitBreakerGateway/DefaultRoute/Resource
  CircuitBreakerGatewayDefaultStageC51956FB:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: CircuitBreakerGateway122B123C
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/CircuitBreakerGateway/DefaultStage/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.67.0,@aws-cdk/assets=1.67.0,@aws-cdk/aws-apigatewayv2=1.67.0,@aws-cdk/aws-applicationautoscaling=1.67.0,@aws-cdk/aws-autoscaling-common=1.67.0,@aws-cdk/aws-cloudwatch=1.67.0,@aws-cdk/aws-codeguruprofiler=1.67.0,@aws-cdk/aws-dynamodb=1.67.0,@aws-cdk/aws-ec2=1.67.0,@aws-cdk/aws-events=1.67.0,@aws-cdk/aws-iam=1.67.0,@aws-cdk/aws-kms=1.67.0,@aws-cdk/aws-lambda=1.67.0,@aws-cdk/aws-logs=1.67.0,@aws-cdk/aws-s3=1.67.0,@aws-cdk/aws-s3-assets=1.67.0,@aws-cdk/aws-sqs=1.67.0,@aws-cdk/aws-ssm=1.67.0,@aws-cdk/cloud-assembly-schema=1.67.0,@aws-cdk/core=1.67.0,@aws-cdk/custom-resources=1.67.0,@aws-cdk/cx-api=1.67.0,@aws-cdk/region-info=1.67.0,jsii-runtime=node.js/v13.12.0
    Metadata:
      aws:cdk:path: TheLambdaCircuitBreakerStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersa0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43S3BucketF9D2DE3B:
    Type: String
    Description: S3 bucket for asset "a0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43"
  AssetParametersa0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43S3VersionKey915B853C:
    Type: String
    Description: S3 key for asset version "a0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43"
  AssetParametersa0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43ArtifactHash33C9198F:
    Type: String
    Description: Artifact hash for asset "a0e924742efa3739f209812573ed2ce217e6459050520a3b6bd1d274342baa43"
Outputs:
  HTTPAPIUrl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CircuitBreakerGateway122B123C
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

